// Auto-generated file. Do not edit manually.
// Generated by: node scripts/generate-quiz-index.js

import { quizData } from './quizdataIFIC1.js';
import { IFIC_Practice_Test2 } from './quizdataIFIC2.js';

export const quizSources = [
  { name: 'IFIC Practice Test 1', data: quizData },
  { name: 'IFIC Practice Test 2', data: IFIC_Practice_Test2 }
];
