export const IFIC_Chapter03 = [
  {
    id: 1,
    question: "What is the primary difference between microeconomics and macroeconomics?",
    options: [
      "Microeconomics studies the economy as a whole, while macroeconomics studies individual markets.",
      "Microeconomics analyzes individual consumers and firms, while macroeconomics focuses on the performance of the economy as a whole.",
      "Microeconomics focuses on government policy, while macroeconomics focuses on corporate behaviour.",
      "There is no difference; they are two terms for the same field."
    ],
    correct: 1,
    feedback: "Microeconomics analyzes the market behaviour of individual consumers and firms, how prices are determined, and how prices determine the production and distribution of goods. Macroeconomics focuses on the performance of the economy as a whole, looking at issues such as unemployment, inflation, and recessions. [Source: Chapter 3, Page 3•4]"
  },
  {
    id: 2,
    question: "According to the Law of Demand, what happens when the price of a good increases?",
    options: [
      "The quantity demanded increases.",
      "The quantity supplied decreases.",
      "The quantity demanded decreases.",
      "The quantity supplied remains unchanged."
    ],
    correct: 2,
    feedback: "According to the Law of Demand, the higher the price the lower the quantity demanded, while the lower the price the higher the quantity demanded, other factors held constant. [Source: Chapter 3, Page 3•5]"
  },
  {
    id: 3,
    question: "According to Chapter 3 - Overview of Economics, what is market equilibrium?",
    options: [
      "The point at which government regulation sets the price of a good.",
      "The price that matches what someone is willing to pay with the price at which someone is willing to supply it.",
      "The maximum price a seller can charge for a product.",
      "The point at which the quantity supplied exceeds the quantity demanded."
    ],
    correct: 1,
    feedback: "Market equilibrium is the price that matches what someone is willing to pay for the product with the price at which someone is willing to supply it — the intersection of demand and supply. [Source: Chapter 3, Page 3•5]"
  },
  {
    id: 4,
    question: "What is gross domestic product (GDP)?",
    options: [
      "The total value of all goods produced by a country's citizens anywhere in the world.",
      "The market value of all final goods and services produced within a country in a given time period.",
      "The total income earned by all residents of a country from foreign investments.",
      "The sum of all government spending in a fiscal year."
    ],
    correct: 1,
    feedback: "Gross domestic product is the market value of all final goods and services produced within a country in a given time period, usually a year or a quarter. [Source: Chapter 3, Page 3•7]"
  },
  {
    id: 5,
    question: "Which of the following is NOT one of the three approaches to measuring GDP?",
    options: [
      "The expenditure approach.",
      "The income approach.",
      "The production approach.",
      "The savings approach."
    ],
    correct: 3,
    feedback: "The three approaches to measuring GDP are the expenditure approach, the income approach, and the production approach. [Source: Chapter 3, Page 3•7]"
  },
  {
    id: 6,
    question: "What does the expenditure approach to calculating GDP measure?",
    options: [
      "The total income generated by producing goods and services.",
      "The sum of personal consumption, investment, government spending, and net exports.",
      "The value added by each industry in the economy.",
      "The total savings of consumers, businesses, and governments."
    ],
    correct: 1,
    feedback: "The expenditure approach measures GDP as the sum of four components: personal consumption (C), investment (I), government spending on goods and services (G), and net exports (X − M). [Source: Chapter 3, Page 3•7]"
  },
  {
    id: 7,
    question: "What is the difference between nominal GDP and real GDP?",
    options: [
      "Nominal GDP includes only goods, while real GDP includes services as well.",
      "Nominal GDP is measured at current prices, while real GDP is adjusted for changes in prices relative to a base year.",
      "Nominal GDP excludes government spending, while real GDP includes it.",
      "There is no difference; the terms can be used interchangeably."
    ],
    correct: 1,
    feedback: "Nominal GDP is the dollar value of all goods and services produced in a given year at prices that prevailed in that same year. Real GDP values production at prices that prevailed in some base year, holding prices constant to establish a better measure of changes in output. [Source: Chapter 3, Page 3•8]"
  },
  {
    id: 8,
    question: "During which phase of the business cycle does the economy experience rising inflation, rising interest rates, and slowing sales?",
    options: [
      "Expansion.",
      "Recovery.",
      "Peak.",
      "Trough."
    ],
    correct: 2,
    feedback: "The top of the cycle is called a peak. It is characterized by demand outstripping supply capacity, rising inflation, rising interest rates, declining business sales, and falling stock prices. [Source: Chapter 3, Page 3•10]"
  },
  {
    id: 9,
    question: "According to Chapter 3 - Overview of Economics, what defines a recession?",
    options: [
      "A single quarter of negative GDP growth.",
      "At least two consecutive quarters of declining real GDP.",
      "A rise in the unemployment rate above 10%.",
      "A decline in stock market prices for three consecutive months."
    ],
    correct: 1,
    feedback: "A popular definition of a recession is at least two consecutive quarters of declining real GDP. When an economy passes its peak and enters a contraction lasting at least two consecutive quarters, it is considered to be in a recession. [Source: Chapter 3, Page 3•10]"
  },
  {
    id: 10,
    question: "Which type of economic indicator tends to peak and trough before the overall economy?",
    options: [
      "Coincident indicators.",
      "Lagging indicators.",
      "Leading indicators.",
      "Composite indicators."
    ],
    correct: 2,
    feedback: "Leading indicators tend to peak and trough before the overall economy, in anticipation of emerging trends in economic activity. They are the most useful and widely used of the economic indicators. [Source: Chapter 3, Page 3•12]"
  },
  {
    id: 11,
    question: "Which of the following is an example of a lagging indicator?",
    options: [
      "Housing starts.",
      "Stock prices.",
      "Unemployment.",
      "Manufacturers' new orders."
    ],
    correct: 2,
    feedback: "Unemployment is a lagging indicator — it changes after the economy as a whole changes. Lagging indicators confirm that a business cycle pattern is occurring. [Source: Chapter 3, Page 3•13]"
  },
  {
    id: 12,
    question: "Which type of unemployment occurs when workers lack the necessary skills to fill available jobs?",
    options: [
      "Cyclical unemployment.",
      "Seasonal unemployment.",
      "Frictional unemployment.",
      "Structural unemployment."
    ],
    correct: 3,
    feedback: "Structural unemployment occurs when workers are unable to find work or fill available jobs because they lack the necessary skills, do not live where jobs are available, or decide not to work at the wage rate offered. [Source: Chapter 3, Page 3•15]"
  },
  {
    id: 13,
    question: "What is the natural unemployment rate?",
    options: [
      "The unemployment rate during a recession.",
      "The minimum level of unemployment below which the rate cannot fall without causing negative economic effects.",
      "The unemployment rate among young workers only.",
      "The rate of unemployment when the economy is at a trough."
    ],
    correct: 1,
    feedback: "The natural unemployment rate is the minimal level of unemployment below which the rate will not drop without causing other negative economic effects. At this level, the economy is thought to be operating at close to its full potential. [Source: Chapter 3, Page 3•16]"
  },
  {
    id: 14,
    question: "According to Chapter 3 - Overview of Economics, which factor influences interest rates by requiring lenders to charge more when there is a risk that borrowers may default?",
    options: [
      "Inflation expectations.",
      "Foreign interest rates.",
      "Default risk.",
      "Central bank credibility."
    ],
    correct: 2,
    feedback: "The greater the risk that borrowers may default on money they have borrowed, the higher the interest rate demanded by lenders. This additional interest rate is referred to as a default premium. [Source: Chapter 3, Page 3•17]"
  },
  {
    id: 15,
    question: "What is the nominal interest rate?",
    options: [
      "The interest rate adjusted for inflation.",
      "The interest rate where the effects of inflation have not been removed.",
      "The interest rate charged by the Bank of Canada on overnight loans.",
      "The interest rate on government bonds only."
    ],
    correct: 1,
    feedback: "The nominal interest rate is one where the effects of inflation have not been removed — for example, the rate charged by a bank on a loan, or the quoted rate on an investment such as a GIC or Treasury bill. [Source: Chapter 3, Page 3•18]"
  },
  {
    id: 16,
    question: "How is the inflation rate calculated using the Consumer Price Index (CPI)?",
    options: [
      "(Current CPI / Previous CPI) × 100.",
      "(Current CPI - Previous CPI) / Previous CPI × 100.",
      "(Previous CPI - Current CPI) / Current CPI × 100.",
      "Current CPI - Previous CPI."
    ],
    correct: 1,
    feedback: "The inflation rate is calculated as: (CPI Current Period - CPI Previous Period) / CPI Previous Period × 100. [Source: Chapter 3, Page 3•20]"
  },
  {
    id: 17,
    question: "What is the main goal of monetary policy in Canada?",
    options: [
      "To maximize government tax revenues.",
      "To regulate the money supply and available credit for sustained economic growth and price stability.",
      "To set the exchange rate for the Canadian dollar.",
      "To manage the federal government's budget deficit."
    ],
    correct: 1,
    feedback: "Monetary policy refers to regulation of the money supply and available credit for the purpose of promoting sustained economic growth and price stability. The Bank of Canada carries out monetary policy primarily through changes to the target for the overnight rate. [Source: Chapter 3, Page 3•23]"
  },
  {
    id: 18,
    question: "If the Bank of Canada buys bonds in the market, what is the expected result?",
    options: [
      "Bond prices will fall, causing interest rates to rise.",
      "The money supply will decrease.",
      "Bond prices will rise, causing interest rates to fall and the money supply to increase.",
      "The Bank Rate will increase."
    ],
    correct: 2,
    feedback: "If the Bank of Canada buys bonds in the market, the price of the bonds will rise, causing interest rates to fall. As a result, the money supply will increase — this is an expansionary policy. [Source: Chapter 3, Page 3•24]"
  },
  {
    id: 19,
    question: "What is the difference between expansionary and contractionary fiscal policy?",
    options: [
      "Expansionary policy decreases spending or increases taxes; contractionary policy increases spending or decreases taxes.",
      "Expansionary policy increases spending or decreases taxes; contractionary policy decreases spending or increases taxes.",
      "Expansionary policy is used only during recessions; contractionary policy is used only during expansions.",
      "There is no difference; both terms describe the same actions."
    ],
    correct: 1,
    feedback: "Expansionary fiscal policy either increases spending or decreases taxes to stimulate the economy. Contractionary fiscal policy either decreases spending or increases taxes to cool off the economy. [Source: Chapter 3, Page 3•25]"
  },
  {
    id: 20,
    question: "What does the current account in the balance of payments record?",
    options: [
      "Financial flows related to investments by foreigners in Canada.",
      "The exchange of goods and services between Canadians and foreigners, earnings from investment income, and net transfers.",
      "Only the merchandise trade balance.",
      "The total amount of foreign debt held by Canadian residents."
    ],
    correct: 1,
    feedback: "The current account records the exchanges of goods and services between Canadians and foreigners, the earnings from investment income, and net transfers such as for foreign aid. [Source: Chapter 3, Page 3•26]"
  }
];
